# Common Labels
labels:
  app: "fiscal-event-service"
  group: "ifix"

namespace: ifix

# Ingress Configs
ingress:
  enabled: true
  zuul: false
  context: "ifix-master-data"

# Container Configs
image:
  repository: "ifix-master-data-service"
replicas: "1"

appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"
java-args: ""

server-context-path: "/ifix-master-data"

# Additional Container Envs
env: |  
  - name: SERVER_SERVLET_CONTEXT_PATH
    value: {{ index .Values "server-context-path" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: SPRING_DATA_MONGODB_URL
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: mongo-db-url
  - name: SPRING_DATA_MONGODB_DATABASE
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: mongo-db-name 
  - name: SPRING_DATA_MONGODB_USERNAME
    valueFrom:
      secretKeyRef:
        name: db
        key: username
  - name: SPRING_DATA_MONGODB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db
        key: password
